lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'wilder03' # Utilizada para cifrar la clave privada
    token_ttl: 7200  # Tiempo de vida del token en segundos (2 hora)

